### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by almusil** [dceara/ovn-heater#103]
I personally find it really hard to go through Python code that is formatted like C. Maybe we could use some 
formatting tool as `Black` [0], which makes the formatting uniform, pythonic and easy to read.

[0] https://github.com/psf/black

**Comment by almusil** [comment]
@dceara @putnopvut WDYT? I can create PR for that if you'll agree.

**Comment by dceara** [comment]
Fixed by https://github.com/dceara/ovn-heater/pull/104
