### ISSUE TITLE
Fails to work with both F32 and F33

### ISSUE THREAD

**Issue by kot-begemot-uk** [dceara/ovn-heater#25]
I am trying to run this using F32 and F33 and in both cases I get: 

docker: Error response from daemon: Conflict. The container name "/registry" is already in use by container "12c6e71a4917bcae404903c1ba3ee69bc18d17c1644abe77c9607bf4ae542ce3". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
./do.sh: line 400: /root/ovn-heater/runtime/browbeat/.rally-ovs-venv/bin/activate: No such file or directory
./do.sh: line 441: /root/ovn-heater/runtime/browbeat/.rally-ovs-venv/bin/activate: No such file or directory

**Comment by dceara** [comment]
@kot-begemot-uk Do you already have a container called "registry" running or stopped?  If it's stopped and it was created by ovn-heater, can you try to remove it (`docker rm registry`) and then retry the installation: `./do.sh install ...`

**Comment by kot-begemot-uk** [comment]
I am starting from blank VMs - Base install, disable GUI, enable NIS and Autofs so they fit into my infra. No other changes.

Same result when doing it with 32 and 33.

**Comment by kot-begemot-uk** [comment]
The culprit is missing: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0" in the vms.

For some reasons, docker instead of aborting installs and then fails the first time on a clean vm. The second time it returns an error which is informative and allows to debug it.

**Comment by dceara** [comment]
There's also a problem in the do.sh script because it doesn't cleanup the stopped registry container.

Running this before `./do.sh install` works around it:
```
docker rm -f registry
```

**Comment by dceara** [comment]
Lots has changed since this issue was opened.  ovn-heater should work fine with more recent versions of fedora (>=34). Closing.
