### ISSUE TITLE
density_heavy test should create a load balancer per iteration

### ISSUE THREAD

**Issue by putnopvut** [dceara/ovn-heater#82]
The density_heavy test currently creates a single load balancer at the beginning of the test. On each iteration, this load balancer has further VIPs/backends provisioned on it.

In actuality, we should not be creating a single monster load balancer, but instead we should be adding a new load balancer during each iteration of the test. This way, we will end up with a number of load balancers equal to the number of iterations, and each of those load balancers will have a small number of VIPs/backends.

**Comment by dceara** [comment]
Fixed by https://github.com/dceara/ovn-heater/pull/83
